language: java
jdk:
  - oraclejdk8
  - openjdk7
install: true
script:
  - "cd modules;mvn clean test"
  - "mvn clean test"
  - "mvn clean package -Dmaven.test.skip=true"

branches:
  only:
    - master 
